x-ege/xege

- man/api/edit/sys_edit.md
- man/api/music/MUSIC.md
- man/api/time/delay_ms.htm
增加 sys_edit类 和MUSIC类的Markdown文档，以及文档的一些小修改
> 增加 sys_edit类 和MUSIC类的Markdown文档

- src/ege.h
- src/egegapi.cpp
`ege::ege_drawtext` 使用 GDI+ API，支持文字半透明绘制。
顺便优化了 #13 的代码。
> 增加 `ege::ege_drawtext` API

- src/ege_head.h
- src/egegapi.cpp
- src/image.cpp
- 修复 #20 导致的在 mingw 下编译失败的 bug
- 合并了一些重复代码
- 实现从资源中加载 png 文件
> 实现加载资源中 png 文件

- src/ege.h
- src/image.cpp
改用误差更小的 Alpha 通道混合算法；
开放 `putimage_alphafilter`
> 改用误差更小的 Alpha 通道混合算法

- src/color.cpp
- src/ege.h
- src/ege_head.h
- src/egegapi.cpp
- src/image.cpp
> 增加 `ege::putpixel_withalpha` 与 `ege::putpixel_withalpha_f`

- man/api/draw/fillrect.htm
- man/api/draw/fillroundrect.htm
- man/api/draw/index.htm
- man/api/draw/roundrect.htm
- src/ege.h
- src/ege_common.h
- src/egegapi.cpp
- 增加绘制圆角矩形函数 （ 做按钮更美观）
- 增加绘制带边框填充矩形函数
> 增加绘制圆角矩形函数 （ 做按钮更美观）

- src/ege_head.h
- src/egegapi.cpp
- src/math.cpp
预计即将发布 21.01 版，作为大改前最后一版与支持 VC6 的最后一版。
> 修复 VC6 兼容性

- src/graphics.cpp
创建窗口后直接显示会有一段时间的白屏，将显示窗口移动到主线程首次刷新窗口后
主线程等待子线程初始化的Sleep函数改为::Sleep，避免转成调用ege自定义的delay_ms
> 将显示窗口从创建线程移到主线程

- src/thread_queue.h
1.修正thread_queue中的错误，循环结束条件不正确，可能导致访问越界
2.将代码中的_r _w改为_begin和_end，以提高可读性
> * 修正: thread_queue process处理错误

- src/ege.h
删除 NAMESPACE_EGE_L 和 NAMESPACE_EGE_R 和 设置GB2312文件编
> 删除 NAMESPACE_EGE_L 和 NAMESPACE_EGE_R 和 设置GB2312文件编码

- src/image.cpp
GDI中的AlphaBlend函数需要源图形做alpha通道预乘处理，否则不能产生正确的结果。
因此，对putimage_withalpha的两个重载函数做如下处理:
（1）对于不支持图片拉伸的版本，改回原先的实现方法，即不使用AlphaBlend，直接逐像素计算；
（2）对于支持图片拉伸的版本，先计算出一个预乘后的图片，然后再使用AlphaBlend进行拉伸贴图。
> 修正putimage_withalpha处理错误

- src/color.cpp
> 在颜色空间转换中使用正确的舍入

- BUILD.md
- CMakeLists.txt
- ege_g++.sh
修改CMakeLists.txt以便自动判断平台，改用mingw-w64工具链编译，添加对应的编译选项。
修改BUILD.md添加linux下编译运行的基本说明。
添加一个linux下工具脚本ege_g++.sh用于简化操作。
> Release/22.08 添加linux编译支持

- man/index.htm
- man/readme.md
* 更正版本号
* 主页单独列出库函数文档
* 官网链接由  http 改为 https
> docs: EGE 20.08 文档修订

- .vscode/c_cpp_properties.json
- RELEASE.md
- demo/ege_input_demo.cpp
- demo/egedemo.cpp
- demo/egemouseball.cpp
- demo/test_setviewport.cpp
- include/ege.h
- include/ege/sys_edit.h
- src/ege_head.h
- src/egegapi.cpp
- src/encodeconv.cpp
- src/encodeconv.h
- src/font.cpp
- src/graphics.cpp
- src/image.cpp
- src/music.cpp
- src/window.cpp
- src/window.h
1. 总是创建 Unicode 窗口
2. 支持在 EGE 中使用 UTF-8 字符串，解决 egedemo 等的乱码问题
> feat: support UTF-8

- include/ege.h
- src/music.cpp
MUSIC 类增加 RepeatPlay() 成员函数，循环播放指定片段
> Feat: MUSIC 类支持循环播放

- include/ege.h
- src/color.h
- src/console.cpp
- src/debug.cpp
- src/ege_head.h
- src/egegapi.cpp
- src/font.cpp
- src/graphics.cpp
- src/image.cpp
- src/image.h
- src/math.cpp
- src/music.cpp
- src/time.cpp
- src/window.cpp
* 将 color_t 类型由  DWORD 修改为 unsigned int, 以减少使用过程中出现的警告
* 对函数参数进行重命名（小驼峰）
* 将 GetAngel 修改为正确的 GetAngle
* 移除未使用的 SHOWCONSOLE 宏
* 对 ege.h 头文件进行排版
> Adjust: 对类型、函数参数，头文件排版等进行调整

- include/ege.h
- src/egegapi.cpp
以 solidxxx 命名，分别是  solidpie, solidcircle, solidellipse, solidrect, solidroundrect, solidpoly 共六种图形
> feat: 添加无边框填充图形

- include/ege.h
- src/egegapi.cpp
> feat: 增加闭合曲线的绘制，以及增加包含 tession 参数的重载

- include/ege.h
- src/ege_graph.h
- src/egegapi.cpp
- src/graphics.cpp
- src/image.cpp
- src/image.h
* 增加设置填充模式
* 增加由控制点数组和类型创建路径的方法
* 分配内存失败时返回 NULL 不抛出异常
> Adjust: Path 功能和行为调整

- src/egegapi.cpp
> adjust: 调整 line 系列函数对当前点的更改

- CMakeLists.txt
This reverts commit 16a7990037edc68a963f30011fac2e28be71b5a7.
> 回退 `/MT` 的修改

- demo/egestar.cpp
修正demo的问题. 此Demo编写的时候, 主流系统还是 32bit 的, 所以用了一个 %d 来接收 HWND 类型, 现在已经不对了, 改正一下
> Demo Bug Fix

- CMakeLists.txt
> Support_both_mt_and_md

- include/ege.h
- src/ege_head.h
- src/egegapi.cpp
- src/graphics.cpp
- src/mouse.cpp
- src/mouse.h
> feat: 增加鼠标扩展键的检测
