x-ege/xege

src/image.cpp
#4 中的问题来自image.cpp中`fix_rect_1size`函数总是认为剪裁区域是全图像，且没有按EGE库的要求（执行setviewport后原点改变）转换坐标，现已修复。
建议设置单独的`setorigin`和`setcliprgn`函数，使裁剪区域与绘图坐标转换相对独立
=> 修复了putimage_xxx系列函数的相关问题

src/graphics.cpp
原`kbmsg`函数调用`peekallkey`时过滤了`key_msg_char`消息且未把它重新放入队列，现传入`flags`=3（相当于`KEYMSG_DOWN_FLAG|KEYMSG_CHAR_FLAG`），可处理`WM_CHAR`消息。
另外，由于默认采用`DefWindowProc`处理消息，故不用专门处理`WM_IME_CHAR`消息，`DefWindowProc`会把它转译成`WM_CHAR`消息。
=> 使getkey可返回key_msg_char型的消息

src/image.cpp
当源图像的绘制部分超出目标的裁剪区时，EGE 在计算实际绘制区域时会少
算 1 行和 1 列。
复现代码：
```c++
#include "ege.h"
int main()
{
ege::initgraph(600, 400);
ege::setbkcolor(ege::YELLOW);
ege::PIMAGE rect = ege::newimage();
ege::resize(rect, 200, 200);
ege::setbkcolor_f(ege::BLUE, rect);
ege::cleardevice(rect);
ege::putimage_alphablend(NULL, rect, 500, 300, 255);
ege::getch();
ege::closegraph();
return 0;
}
```
运行结果：
可见最右列和最底行仍然是背景色黄色
=> 修复计算绘制区时计算失误

src/ege.h, src/egegapi.cpp
#11 中：
> putpixels和putpixels_f像素颜色赋值方式修正，由BGR改为RGB
> clearviewport清除视口区域是直接用bar糊上去的，这样颜色实际是填充颜色，建议修正为用背景颜色填充。
请 @GWMforget1997 测试
=> 修复两个颜色相关 bug

src/egegapi.cpp
#11 中
> setlinewidth()仅仅是设置一下线宽参数，实际需要在setcolor调用后生效，修正为立即生效
> setlinestyle()，当线宽大于1时，线型失效
=> 修正关于线型设置的 bug

src/egegapi.cpp
来自 #11 
> ege_setalpha, PIMAGE参数为NULL时，程序会崩溃退出
=> 修正 `ege_setalpha` 当传入 NULL 时段错误的 bug

.gitignore, src/ege.h, src/ege_head.h, src/egegapi.cpp, src/graphics.cpp
- 增加函数 `ege::seticon`，支持通过传入图标资源 ID 设置 EGE 窗口图标。
- 允许在 `ege::initgraph` 之前调用 `ege::setcaption` 或 `ege::seticon`
- 增加初始化选项 `INIT_UNICODE`，可由使用者选择创建 Unicode 窗口
- 将一些函数调用由宏改为显式调用 ANSI/UNICODE 版本
=> 自定义窗口图标和创建 UNICODE 窗口

src/ege_head.h, src/graphics.cpp
- 将版本宏定义移到 ege_head.h 中
- 去掉全局变量中的 `window_class_name`，以编译期常量代替
- 使用全局变量的默认构造函数自动初始化窗口标题
=> 重构 global_settings 一些变量

demo/egedemo.cpp, src/ege.h, src/ege_head.h, src/egegapi.cpp, src/graphics.cpp, src/image.cpp
把 `IMAGE::newimage` 一坨代码重构了。`IMAGE` 就是管理内存设备上下文（DC）的类，可以直接通过 `GetDC(NULL)` 得到屏幕 DC，然后用它建立内存 DC，因此不用先调用 `initgraph` 建立窗口。
关键 commit 是 04c1ae1。
无长宽参数时默认建立 1×1 大小的 `IMAGE` 对象保持不变，但允许建立长或宽为 0 的 `IMAGE` 对象以及将 `IMAGE` 对象的长或宽 `resize` 到 0 大小。
=> 部分重构 IMAGE 类

src/graphics.cpp
在 `initgraph` 前调用 `setinitmode`，以 `setinitmode` 为准
=> 修正初始化标志位设定的行为

src/ege_head.h, src/egegapi.cpp, src/image.cpp
=> 使用字符串类管理内存

src/ege.h, src/graphics.cpp
不带 Flag 参数仅用长宽调用 `initgraph`，则在 Release 配置启动时显示 Logo，在 Release 时则不显示。
新增函数 `getinitmode`。
将兼容 BGI 的 `initgraph` 重载版本的 `path` 参数类型改为 `const char*`。
=> 修改 `initgraph` 的定义，使代码更清晰

src/image.cpp
`getimage_from_IPicture` 函数使用全局 DC，现改为使用 `::GetDC(NULL)` 获取
=> fix(graphics): 修复在 `initgraph` 前调用 `getimage` 时出错

src/egegapi.cpp
解决 #44 
问题来自 EGE20.08 取消了 `resize` 会执行 `cleardevice` 的假设。
=> fix(graphics): 修复 inputbox_getline 界面发黑的问题

man/api/index.htm, man/api/macro/index.htm, src/ege.h
目前ege.h中直接include windows.h文件，导致IDE智能提示时会显示大部分的Windows API，这其实是不必要的。
因此，当_EGE_FOR_AUTO_CODE_COMPLETETION_ONLY_宏被定义时，ege.h不包含windows.h而只包含winuser.h, wingdi.h和windef.h
这样不会影响EGE的正常编译和使用
=> 当IDE出于智能提示的目的读取ege.h时，不包含windows.h

demo/egealpha.cpp, src/ege.h, src/ege_head.h, src/egegapi.cpp, src/image.cpp
目前所有的ege_系列函数都在内部创建一个Graphics对象，处理后释放。
这会影响图像绘制时的性能。
这个Patch在Image对象内部缓存了Graphics对象和Pen对象。ege_系列函数在绘图时会使用这两个缓存的对象，不在创建新对象。
为了节省资源，这两个对象使用延迟加载，只有在第一次使用时才会被创建。
为了提高速度，相关函数做成了inline的形式。
请大家审核吧
=> 在Image对象中缓存Graphics和Pen对象

src/ege.h, src/ege_head.h
目前ege_系列高级作图函数定义在ege.h中，实现在egegapi.cpp中。
在实现部分，会根据EGE_GDIPLUS宏是否定义来决定是否实现；而在ege.h中并未做该判断。
因此，将EGE_GDIPLUS宏放到ege.h中，并根据该宏是否被定义来决定是否要定义ege_系列高级作图函数
btw:
不知道为什么git老是认为我修改了putimage_rotatetransparent的定义。实际上没有修改；我直接从github上手工下载一个最新的ege.h来做修改，它仍然认为putimage_rotatetransparent这部分有变化。不理解了
=> 将EGE_GDIPLUS宏放到ege.h中

demo/ege_new_drawimage.cpp, man/api/draw/ege_drawimage.htm, man/api/draw/ege_get_transform.htm, man/api/draw/ege_set_transform.htm, man/api/draw/ege_transform_reset.htm, man/api/draw/ege_transform_rotate.htm, man/api/draw/ege_transform_scale.htm, man/api/draw/ege_transform_translate.htm, man/api/draw/index.htm, src/ege.h, src/egegapi.cpp
ege_drawimage用于实现带alpha混合的绘图，共有两个重载函数：
- 一个仅指定绘制左上角坐标，以方便使用；
- 另一个支持缩放，需要提供完整的坐标和长宽参数
ege_transform系列函数用于进行坐标变换设置，此设置对目前所有的ege绘图函数均有效。包括：
- 获取坐标变换矩阵；
- 设置坐标变换矩阵
- 平移/旋转/缩放
- 清除坐标变换设置
- 计算当前变换后点的新坐标
使用方法可见demo目录下的ege_new_drawimage.cpp
=> 增加ege_drawimage和ege_transform系列函数

demo/egedemo.cpp, man/api/img/index.htm, man/api/img/resize_f.htm, src/ege.h, src/ege_head.h, src/egegapi.cpp, src/image.cpp
从 #44 可见之前的修改是个错误，他还是个 break change，还很容易被误用，一般以绘图为目的的使用中 resize 后总是要填充背景的。
=> 将 ege::resize 函数的行为改回会填充背景色，并增加不填充背景色的 ege::resize_f 函数

demo/multiplesys_edit.cpp, src/ege/egecontrolbase.h, src/ege/sys_edit.h, src/egegapi.cpp, src/graphics.cpp
之前sys_edit继承自egeBaseControl的isfocus()方法并没有真正实现，程序无法用它来判断某控件是否获得了焦点
本次修改 使其真正可用
=> 使sys_edit的isfocus()方法可用

src/ege.h
gcc在使用C++ 11或以上语言标准编译时，下面的代码编译失败：
#include <graphics.h>
#define COLOR_NUM	5	//小球颜色种类数目
color_t colors[COLOR_NUM] = {RED,BLUE,EGERGB(255,0,0)};
int main() {
return 0;
}
本PR尝试修正这个问题。
=> 修正：无法将颜色常量用于颜色数组的初始化

src/ege.h
目前ege.h中直接包含了wingdi.h，使IDE在解析ege.h和补全提示时，会同时提示wingdi.h中包含的符号，容易导致用户选择，如误用RGB等。
本PR让支持EGE_FOR_AUTO_CODE_COMPLETETION_ONLY宏的IDE（如小熊猫Dev-Cpp)可以在解析ege.h时忽略wingdi.h，以在不影响正常编译的前提下减少上述问题。
=> 使支持EGE_FOR_AUTO_CODE_COMPLETETION_ONLY宏的IDE在解析代码时忽略wingdi.h

demo/egesnake.cpp, src/ege.h
在颜色宏中使用完整路径 ::ege::color_t 进行强转。
=> fix: 修复 color_t 和 EGE 颜色宏引起的编译错误

src/graphicstest/maintest.cpp
这句 `scanf("%*s")` 从一开始就存在，不知道有啥用。
删掉之后就能修复 #74 。
=> fix: 删除主测试代码中的 scanf 调用

src/egegapi.cpp, src/graphicstest/maintest.cpp
通过调用timeBeginPeriod函数，将windows的时钟服务精度明确设置为1ms，以确保ege_sleep的精度。
=> 确保ege_sleep精度

src/graphics.cpp
bug 在 e66176 提交中引入：将 ShowWindow() 从 创建窗口的线程移动到了主线程，而在主线程中调用ShowWindow()只能显示窗口而无法使其激活并获得焦点。
=> fix:修复程序运行后图形窗口无法激活获得焦点的问题

src/ege.h, src/graphics.cpp
这个属于之前遗漏的标志位，_getkey()返回的值中，已经用 KEYMSG_FIRSTDOWN 标志位标记按键按下时第一次发送的down类型消息，但是在getkey()中没有将这个标志位提取到key_msg结构体的flags成员中。
=> fix:标记按键按下时第一次发送的down消息

src/image.cpp
在Image对象中缓存了gdi+ graphics对象。
在处理Image对象的enable_aa属性时，只更新了graphics对象的图形反锯齿，未正确设置和更新graphics对象的文字反锯齿。
=> 修正：未设置gdi+ graphics对象的文字反锯齿属性

src/egegapi.cpp
造成 delay_ms(0) 较高延时的两个因素：
- delay_ms(0) 里加入了一个固定延时 ege_sleep(1)，这个延时在默认设置下通常是 15 到 17ms (EGE 使用了 timePriodBegin(1) 将定时器周期设置为 1 ms，所以额外延时是 1 到 2 ms) 。
- 代码里加了个 setviewport() 设置视口区域，但视口区域并没有做任何修改，应该是多余的，并且对帧率有不小的影响。刷新时不应该改变视口区域。
现在将 ege_sleep(1) 改为 ege_sleep(0)，Sleep() 函数在微软文档里的描述是 "如果值为0，则线程会将其时间片的剩余部分放弃给已准备好运行的任何其他线程。 如果没有其他线程可供运行，函数将立即返回，并且线程继续执行。"
=> 修复 delay_ms(0) 延时过高的问题

src/ege.h, src/ege_head.h, src/graphics.cpp, src/graphics.h
* 将内部头文件的版本宏移动到公开头文件中
* 版本号数值(6位十进制数)改为 long 型，getGraphicsVer() 返回值类型改为 long
* ege.h 和 graphics.h 的文件注释中增加版本信息，方便查看版本
=> Feature: 公开头文件中加入版本宏

src/egegapi.cpp
在文字对齐方式设置为垂直居中时，如果文本输出方向并非为水平从左到右（即 角度为 0°），会出现文本对齐错误、文本发生偏移的情况。
=> fix: 解决文本垂直居中对齐出错问题

include/ege.h, src/image.cpp, src/image.h
**问题**
像素颜色格式为 RGB 的图像，读取后透明通道为 0，这和 ege 中的 RGB 颜色 alpha = 0xFF 的颜色表示不符，导致 putimage_withalpha() 无法绘制出图像。
EGE 中的像素颜色格式为 ARGB, 对于不含透明通道的图像，加载后 Alpha 应以 0xFF 填充。
**实现**
ege 中非 PNG 图片使用 OleLoadPicture() 接口加载，然后从 IPicture 对象中解析出图像数据，但这个 IPicture 无法判断图像是否具有透明通道，因此非 PNG 图像改为使用 GDI+ Bitmap 实现图像读取。
PNG 格式：(由 libpng 读取)
- 额外增加 16 位深度(每通道)格式的判断，将其转换成 8 位深度。
- 读取前传入缓存区地址，避免额外复制操作。
- RGB 格式则添加 alpha 通道，以 `0xFF` 填充
非 PNG 格式：
- 参考 MFC 源码中的 CImage::CreateFromGdiplusBitmap() 实现，将原来 OleLoadPicture() 接口改为使用 GDI+ Bitmap 读取。
- 将像素颜色格式转换为 32 位 ARGB (RGB 格式转换成 ARGB 后 alpha 为 `0xFF` )
- **读取时会有一次将图像数据从 Bitmap 复制到 PIMAGE 图像缓冲区的过程，目前没找到可以直接移交图像数据而避免复制的方法**
**性能**
本地测试读取速度有 4~10 倍提升，可能是原来的接口解析速度太慢。
=> Fix: 修复读取 RGB 格式图像后透明通道为 0 的问题

src/ege_graph.h, src/graphics.cpp, src/image.cpp
原因: 在创建图像时创建了 GDI+ 对象但并未在此之前对 GDI+ 进行初始化 。#59 中引入(083423f)
=> Fix: 修复在 inigraph() 之前调用 newimage()  会引起程序崩溃的问题

src/image.cpp
1.  加载 PNG 图片时很可能会在控制台中弹出大批量的 "libpng warning: iCCP: known incorrect sRGB profile" 警告，十分影响控制条输入输出、调试和阅读。 
2. 各个浏览器、图像软件的做法一般都是直接忽略颜色空间信息以 sRGB 颜色空间进行显示。
3. 图像软件在保存时，有时会嵌入颜色空间信息，一般都是各自默认的颜色空间，这些颜色空间其实都是 sRGB。作为专业的图像处理软件，肯定考虑到了 PNG 图像在各个软件中显示的问题。由图像软件生成的图像有很大的可能会在这个图像软件上再次编辑，这个颜色空间在该软件中就是最正确的，没必要让用户进行修改，否则图像软件可能还会提示让用户转换回该软件默认的颜色空间。
根据官方手册中提供的方法 ([libpng-manual](https://github.com/pnggroup/libpng/blob/f1848a3b560ddcad065242268433af475948461e/libpng-manual.txt#L5122)) 进行屏蔽。
=> chore: 屏蔽 "libpng warning: iCCP: known incorrect sRGB profile" 警告

include/ege.h, src/ege_graph.h, src/egegapi.cpp, src/graphics.cpp, src/window.cpp
功能为将当前显示页(Visual Page)中的图像数据复制到窗口帧缓冲区。
- 在默认不设置绘图页的情况下, 用于显示和绘图的是同一个绘图页, 所以这个能够将绘图内容直接显示到窗口上,。
- 如果用户主动改变了绘图页,则需要用户自己控制显示页, 在绘图完成后, 将显示页和绘图页进行切换后再调用 flushwindow() 进行刷新
=> Feat: 增加 flushwindow() 函数, 用于将后台帧缓冲中的内容显示到窗口

src/CMakeLists.txt, src/ege_common.h, src/ege_dllimport.cpp, src/ege_dllimport.h, src/ege_graph.h, src/egegapi.cpp, src/graphics.cpp, src/image.cpp, src/music.cpp, src/time.cpp
* 并未链接的库 (uuid, oleaut32)
* 改为运行时加载,显示链接的库 (ole32, msimg32, imm32, winmm)
修改后只需额外链接  gdi32 和 gdiplus
=> Build: 移除并未链接的库, 将部分静态链接的库改为运行时加载,显式链接 

src/debug.cpp, src/ege_dllimport.h, src/encodeconv.cpp, src/image.h, src/type.h, src/window.h
=> fix compile error on mingw-w64 (rename Windows.h => windows.h)

build_commands.bat
如题。build_commands.bat总体上仍然正常工作，但其上次更新为四年前以至于尚未支持vs2022的自动构建。
尽管vs2019的库文件与vs2022的库文件兼容，但在只安装了vs2022而未安装vs2019时此脚本不会正确产生库文件，出于本库定位为初学者库的关系，不妨简单地增加此功能。
主要改动是增加了如下一句：
```bat
:: Visual Studio 2022 64bit
cmake -G "Visual Studio 17 2022" -A x64 -S . -B build\vs2022_64 -DCMAKE_ARCHIVE_OUTPUT_DIRECTORY_RELEASE="%CD%\build\lib\vs2022\x64"
cmake --build build\vs2022_64 --config Release -j
```
经本地测试能够正常产生64位时的lib文件，且库正常工作。
=> 修改build_commands.bat以支持vs2022快速构建

include/ege.h, src/image.cpp, src/image.h
暂时先采用 GDI+ DrawImage 实现，缺点是非常耗时，后续再考虑优化问题。
原来出现错位是计算区域时用了 fix_rect_1size() ，这个仅能计算 1:1 大小的，缩放没有按比例调整。
=> fix: 修复 putimage_withalpha() 缩放绘制版本错位的问题，并添加平滑处理选项

src/egegapi.cpp
改为使用语义更为清晰的 CreateSolidBrush() 来创建画刷
=> Typo: 纠正 setfillcolor() 创建画刷时赋值对象不正确的错误

src/egegapi.cpp
drawpoly() 和 ege_drawpoly() 内部都使用 折线 PolyLine 来实现,。如果直线线帽和直线连接样式为圆角，那么首尾连接处不进行额外处理也是可以正常连接的，但是如果是斜角和尖角的就出问题。
所以这里对首先连接的闭合折线使用 Polygon() 来进行绘制
=> fix: 修复 drawpoly(), ege_drawpoly() 在绘制形成多边形的闭合折线时首尾连接处无拐角的情况

include/ege.h, src/color.cpp, src/color.h, src/ege_math.h, src/egegapi.cpp, src/image.cpp, src/image.h, src/type.h
修改为常用的 AlphaBlend 算法。公式为：
A = A(dst)  + alpha * (1.0    - A(dst));
R = R(dst)  + alpha * (R(src) - R(dst));
G = G(dst) + alpha * (G(src) - G(dst));
B = B(dst)  + alpha *  (B(src) - B(dst));
修改后可完成图层绘图功能。缺点是耗时增加 2~3 倍 (MSVC 优化不如 GCC)。
=> Adjust: 消除 alphablend 误差

include/ege.h, src/font.cpp
- rectprintf 内部使用的 DrawText()，这个函数和 TextOut() 使用的同一个对齐设置，而是通过其参数来控制文本对齐方式。
- DrawText() 内部在输出多行文本时并不支持垂直方向对齐，但是给出了输出区域的宽高，因此可以通过设置偏移来达到垂直方向对齐的目的。
- 但是裁剪只会对超出区域末尾的文本进行，通过偏移的方式虽然达到了垂直对齐的目的，但是改变了原本的输出区域，造成裁剪不正确。如果文本是底部对齐且行数超出范围，往上偏移之后会使得顶部文本超出原本的矩形区域。这个可以通过设置裁剪区域来解决，求出矩形区域与原本裁剪区域的交集作为新的裁剪区域，设置后再恢复恢复回原来的裁剪区域。
=> fix: 解决矩形区域输出文本无法正确对齐的问题

include/ege.h
默认的文本对齐方式应该是顶部对齐、左对齐，底层也是如此。因此 LEFT_TEXT 和 TOP_TEXT 的枚举值应设置为 0.
=> adjust: 调整文本垂直对齐方式的枚举值

include/ege.h, src/egegapi.cpp
ege 中的 drawpoly() 来自于 BGI，用于绘制折线，当折线首尾相连时就是多边形。
- 但是绘制多边形需要传入 N+1 个点，并且设置首尾两个端点相等，这就给用户增加额外的操作负担，不是一个好的设计。
- 而且由于线宽、线帽和直线联结样式的问题，即使首尾相连，使用多边形和折线也不是同一个图形，如果用户真的想绘制折线而不是多边形，那么是无法做到的。
因此增加折线 polyline 和多边形 polygon 两种接口，这也是目前常见的做法。
=> feat: 增加折线 polyline 和多边形 polygon

src/egegapi.cpp, src/image.cpp
通过设置了裁剪区域的 HDC 创建的 Graphics 后续无法再此区域外绘制，调整 Graphics 的裁剪区域也不行，创建前需要先取消 SelectClipRgn() 取消裁剪。
=> fix: 修复调整窗口大小时，GDI+ 裁剪区域错误的问题

include/ege.h, src/egegapi.cpp, src/font.cpp, src/image.cpp, src/image.h
文本颜色通常很少改动，而线条颜色经常变换。如果文本颜色和线条颜色不相同，则绘图时需要频繁切换，如果忘记则出现颜色不正确。
GDI/GDI+ 这两个颜色是分开设置的，同时设置不利于颜色的控制，故增加 line color 和 text color，而原来的 setcolor() 含义是设置前景色，依然是同时控制两个颜色保持不变。getcolor() 返回的是 line color，在不单独设置的情况下和原来没有区别，如果两种颜色不同，则前景色以 line color 为准。
=> feat: 线条颜色和文本颜色可单独设置，setcolor() 前景色则同时设置线条颜色和文本颜色

include/ege.h, src/ege_graph.h, src/egegapi.cpp, src/image.cpp, src/image.h
设置线帽 setlinecap
获取线帽样式 getlinecap
一共支持三种基础线帽样式，flat(平头), square(方头), round(圆头)
- GDI 仅支持线条两端使用同样的线帽，而 GDI+ 两端线帽可以不相同，故增加可分别设置两端线帽的 setlinecap 重载
- 默认为 flat，这个是大多数图形库所默认使用的线帽样式
- 上面三种是大多数图形库都支持的线帽样式，而 GDI+ 支持更多非基础线帽样式，暂时不加入，待后续考虑。
=> feat: 增加线帽设置

include/ege.h, src/ege_graph.h, src/egegapi.cpp, src/image.cpp, src/image.h
统一样式，之前线条连接点样式并不统一，GDI 的设置为 圆角，而 GDI+ 设置为尖角。现在统一使用各图形库默认设置的尖角。
=> feat: 增加线条连接点样式设置，默认样式为尖角

include/ege.h, src/egegapi.cpp
ege_drawpoly 可同时绘制折线和多边形，首尾不相连时绘制折线，首尾相连时绘制多边形。多边形需要多创建一个冗余的点，并且有线帽和连接点样式的缘故，即使首尾相连，用户并不一定是想绘制多边形。因为将多边形和折线这两个绘图分离。
=> feat: 增加 ege_polyline 和 ege_polygon

src/egegapi.cpp
=> Fix: 修复调用 setviewport 后GDI+绘图坐标系原点未修改的问题

.gitignore, src/keyboard.cpp
使用 GetOpenFileName 等打开对话框后，keystate 失效，但按键消息正常。原因是 GetKeyState 是通过处理按键消息来判断按键状态，需要在消息队列的窗口线程中使用。（如果在其它线程，猜测目前的底层实现是会获取最新创建的一个窗口线程的按键状态，因此一开始未打开对话框时是正常的。）。
=> Fix: 修复 keystate 在打开对话框后失效的问题

CMakeLists.txt, tasks.sh
有助于使用者进行 release 时， 不用依赖 msvcrt
=> 在 windows 上开启 '/MT' 选项

.gitignore, src/egegapi.cpp
GDI 有两种[笔类型](https://learn.microsoft.com/zh-cn/windows/win32/api/wingdi/nf-wingdi-extcreatepen)：`PS_GEOMETRIC` 和 `PS_COSMETIC`。
- PS_GEOMETRIC支持不同的线宽、线帽、线连接处样式等多种直线样式，但是绘制非常缓慢。
- PS_COSMETIC 仅支持线宽为1的直线，并且虚线类型有 bug，无法正确绘制，但是绘制较为快速 (线宽为 1 的情况下，速度是 PS_GEOMETRIC 的 4 倍 )
线宽为1时，线帽、线连接处样式等无区别，所以可以在直线线宽为 1 且线型为 SOLID_LINE 或 NULL_LINE 时使用 PS_COSMETIC 类型。
ege 内部自己实现的 line_f() 更为快速，速度大约是使用 PS_COSMETIC 笔类型时的 6 倍。缺点是，line_f() 只支持线宽为1的无线帽的实线，并且不支持设置二元光栅操作。
=> Perf:  提高默认样式的直线的绘制速度

tasks.sh, utils/release.sh
如题， 主要支持 vs2022/vs2019/vs2017/vs2015/vs2010, 其他平台可以后续再补充
=> 增加一键打包发布的脚本，减少发版负担。

CMakeLists.txt
=> 非 MSVC 编译增加 -fno-exceptions, 不使用异常

src/image.cpp
函数参数应为false，原始参数true会导致无限递归从而引发栈溢出
=> [BUG修复]修正IMAGE::gentexture的会引发栈溢出的函数参数

src/ege_graph.h, src/ege_head.h, src/egegapi.cpp, src/graphics.cpp, src/image.cpp, src/image.h
- 在绘图环境初始化之前调用，getcolor(), getbkcolor(), getfillcolor() 将返回绘图环境初始化时所设置的默认颜色值。
- setbkcolor(), setbkcolor_f() 允许在绘图环境初始化之前调用，以预先设置窗口背景色，避免重复填充的同时减少屏幕闪烁
=> adjust:  调整在环境初始化之前所返回的颜色值，以及允许预先设置窗口背景色

tasks.sh, utils/deploy.sh
CMake 里面新增了 EGE_BUILD_DEMO 选项， 但是根目录的 tasks.sh 没有做对应的适配， 导致 vscode 的指令无法正确执行。这里修正一下
=> fix demo build error
